export const JOB_NAME = {
  SEND_WELCOME_EMAIL: 'SEND_WELCOME_EMAIL',
  SEND_OTP_EMAIL: 'SEND_OTP_EMAIL',
  SEND_CONFIRMATION_EMAIL: 'SEND_CONFIRMATION_EMAIL',
  SEND_CONFIRMATION_WHATTSUP: 'SEND_CONFIRMATION_WHATTSUP',
} as const;
